// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Fullscreen","status":true,"description":"Starts the game in fullscreen","parameters":{}},
{"name":"SplashScreen","status":true,"description":"","parameters":{}}
];
