// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Fullscreen","status":true,"description":"Starts the game in fullscreen","parameters":{}},
{"name":"SplashScreen","status":true,"description":"","parameters":{}},
{"name":"TextPicture","status":false,"description":"Displays text as a picture.","parameters":{}},
{"name":"RF_CustomWindowMessage","status":false,"description":"(v.1.0) Create custom window. View documentation for plugin commands.","parameters":{}}
];
